### ISSUE TITLE
cannot make it work properly

### ISSUE THREAD

**Issue by albgen** [erikn69/ZplEscPrinter#1]
Hello,

I see the following when printing on the emulator but on the paper i see it complete.

![image](https://github.com/user-attachments/assets/f4cb1443-6cdd-490f-9c37-b3122f4be487)

**Comment by erikn69** [comment]
this app use [receipt-print-hq/escpos-tools/esc2html.php](https://github.com/receipt-print-hq/escpos-tools/blob/master/esc2html.php) and [mike42/escpos-php](https://github.com/mike42/escpos-php) for render

If it doesn't work, you are using an unsupported command, or you are sending the raw text incorrectly.

Paste the raw text in base64 (so that no bytes are lost), to take a look

**Comment by erikn69** [comment]
this app use [receipt-print-hq/escpos-tools/esc2html.php](https://github.com/receipt-print-hq/escpos-tools/blob/master/esc2html.php) and [mike42/escpos-php](https://github.com/mike42/escpos-php) for render

If it doesn't work, you are using an unsupported command, or you are sending the raw text incorrectly.

Paste the raw text in base64 (so that no bytes are lost), to take a look

Look with this file:  [qzind/tray/assets/escpos_sample.bin](https://github.com/qzind/tray/blob/master/assets/escpos_sample.bin)
![image](https://github.com/user-attachments/assets/7c306c58-fb0b-47b1-b34b-38101845bfe1)

**Comment by erikn69** [comment]
Example with img: [receipt-print-hq/escpos-tools/receipt-with-logo.bin](https://github.com/receipt-print-hq/escpos-tools/blob/master/receipt-with-logo.bin)

![image](https://github.com/user-attachments/assets/f3aa588a-467f-4739-8f9d-be3488b1f17f)

Closed due inactivity
